spring.application.name=edu360-management-system

# =========================
# DATABASE CONFIG
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate

# =========================
# JWT CONFIG
# =========================
edu360.app.jwtCookieName=${JWT_COOKIE_NAME}
edu360.app.jwtSecret=${JWT_SECRET}
edu360.app.jwtExpirationMs=${JWT_EXPIRATION}

# =========================
# CORS
# =========================
cors.accepted=*

# =========================
# MAIL SERVER CONFIG
# =========================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# =========================
# STMP MAIL CONFIG
# =========================
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.default-encoding=UTF-8

# =========================
# VIETQR CONFIG
# =========================
payment.vietqr.bankCode=${VIETQR_BANK_CODE}
payment.vietqr.accountNumber=${VIETQR_ACCOUNT_NUMBER}
payment.vietqr.accountName=${VIETQR_ACCOUNT_NAME}
payment.vietqr.templateId=${VIETQR_TEMPLATE_ID}
payment.vietqr.baseUrl=${VIETQR_BASE_URL}

# =========================
# GOOGLE OAUTH2 CONFIG
# =========================
google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}


# =========================
# ENROLLMENT CONFIG
# =========================
enrollment.requirePaid=${ENROLL_REQUIRE_PAID}

# =========================
# CASSO WEBHOOK CONFIG
# =========================
casso.webhook.secret=${CASSO_WEBHOOK_SECRET}

# =========================
# CLOUDINARY CONFIG
# =========================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
