spring.application.name=edu360-management-system
spring.datasource.url= jdbc:mysql://localhost:3306/edu360_system?useSSL=false
spring.datasource.username= root
spring.datasource.password= 123456

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update

# App Properties
edu360.app.jwtCookieName= edu360
edu360.app.jwtSecret= ======================edu360=Spring===========================
edu360.app.jwtExpirationMs= 86400000

# CORS
cors.accepted=*