spring.application.name=edu360-management-system
spring.datasource.url= jdbc:mysql://localhost:3306/edu360_system?useSSL=false
spring.datasource.username= root
spring.datasource.password= 123456

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update

# App Properties
edu360.app.jwtCookieName= edu360
edu360.app.jwtSecret= ======================edu360=Spring===========================
edu360.app.jwtExpirationMs= 86400000

# CORS
cors.accepted=*

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=crush1003ahihi@gmail.com
spring.mail.password=zpxtpooxngkiwkui
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Tu? ch?n:
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.default-encoding=UTF-8

# VietQR config
payment.vietqr.bankCode=970422
payment.vietqr.accountNumber=123456789
payment.vietqr.accountName=TRUNG TAM EDU360
payment.vietqr.templateId=compact2
payment.vietqr.baseUrl=https://api.vietqr.io/image
